apiVersion: v1
kind: PersistentVolume
metadata:
  name: msgb-volume
  namespace: msgb
  labels:
    type: local
spec:
  storageClassName: linode-block-storage-retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"