apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: minio
  name: minio
  namespace: msgb # Change this value to match the namespace metadata.name
spec:
  replicas: 1
  selector:
    matchLabels:
      lbtype: broker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        lbtype: broker
        app: minio
    spec:
      containers:
        - name: minio
          image: quay.io/minio/minio:latest
          command:
            - /bin/bash
            - -c
          args:
            - minio server /data --console-address :9090
          env:
            - name: MINIO_ACCESS_KEY
              value: "minio"
            - name: MINIO_SECRET_KEY
              value: "minio123"
          volumeMounts:
            - mountPath: /data
              name: minio-volume # Corresponds to the `spec.volumes` Persistent Volume
          ports:
            - containerPort: 9090
            - containerPort: 9000
      volumes:
        - name: minio-volume
          persistentVolumeClaim:
            claimName: minio-pvc
