apiVersion: v1
kind: Pod
metadata:
  labels:
    app: minio
  name: minio
  namespace: msgb # Change this value to match the namespace metadata.name
spec:
  containers:
    - name: minio
      image: quay.io/minio/minio:latest
      command:
        - /bin/bash
        - -c
      args:
        - minio server /data --console-address :9090
      env:
        - name: MINIO_ACCESS_KEY
          value: "minio"
        - name: MINIO_SECRET_KEY
          value: "minio123"
      volumeMounts:
        - mountPath: /data
          name: minio-volume # Corresponds to the `spec.volumes` Persistent Volume
      ports:
        - containerPort: 9090
        - containerPort: 9000
  # No real idea what this means just yet.
  # nodeSelector:
  #   kubernetes.io/hostname: kubealpha.local # Specify a node label associated to the Worker Node on which you want to deploy the pod.
  # nodeSelector:
  #   docker.io/hostpath: hostpath
  volumes:
    - name: minio-volume
      persistentVolumeClaim:
        claimName: minio-pvc
  # hostPath: # MinIO generally recommends using locally-attached volumes
  #   path: /mnt/disk1/data # Specify a path to a local drive or volume on the Kubernetes worker node
  #   type: DirectoryOrCreate # The path to the last directory must exist
