{{- if .Values.RabbitMQ.service.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.RabbitMQ.name }}{{ .Values.RabbitMQ.service.suffix }}
  labels:
    {{- include "bean-service-mesh.labels" . | nindent 4 }}
spec:
  type: {{ .Values.RabbitMQ.service.type }}
  selector:
    app: {{ .Values.RabbitMQ.name }}-selector
  ports:
    {{- if .Values.RabbitMQ.service.console.enable }}
    - name: {{ .Values.RabbitMQ.name }}{{ .Values.RabbitMQ.service.suffix }}{{ .Values.RabbitMQ.service.console.suffix }}
      protocol: {{ .Values.RabbitMQ.service.console.protocol }}
      port: {{ .Values.RabbitMQ.service.console.port }}
      targetPort: {{ .Values.RabbitMQ.service.console.targetPort }}
    {{- end}}
    - name: {{ .Values.RabbitMQ.name }}{{ .Values.RabbitMQ.service.suffix }}{{ .Values.RabbitMQ.service.api.suffix }}
      protocol: {{ .Values.RabbitMQ.service.api.protocol }}
      port: {{ .Values.RabbitMQ.service.api.port }}
      targetPort: {{ .Values.RabbitMQ.service.api.targetPort }}
{{- end}}

